### PR TITLE
Setup the basic structure for the controller Ricky wanted to add the …

### PR DESCRIPTION
**Pull request by AndrewBurke87**
…thens and the catches

### CODE REVIEW

**Review by krcook1980 — CHANGES_REQUESTED** [review]
APP.js, unsure that stuff goes in there. 
Utils.js has api/recipes?
controller is full of Post... should match the name of the model made for the database

**Comment by krcook1980** [comment]
changes pending

**Comment by AndrewBurke87** [comment]
resubmitted

**Review by krcook1980 — APPROVED** [review]
Thank you!

**Pull request merged**
